server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tl-study-admin?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password:
    druid:
      stat-view-servlet:
        # 访问 /druid/index.html
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: root
        login-password: root
        allow:
        deny:
      filter:
        stat:
          log-slow-sql: true
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  rabbitmq:
    host: 60.205.231.241
    port: 5672
    virtual-host: zhaojie
    username: zj
    password: zj
    listener:
      simple:
        #手动签收
        acknowledge-mode: manual
        #线程并发数
        concurrency: 5
        #最大线程并发数
        max-concurrency: 10

logging:
  level:
    com.tuling.mapper: debug
